title: GameCast
description: This project is designed to facilitate the creation of async multiplayer games using a lightweight server-client architecture.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template